In [1]:
import pandas as pd

# 1. DEFINITIONS [SATZARTEN]

## SATZART-10 [Landdaten]
```Datensatzbeschreibung_GV100AD.pdf```, page 2

In [31]:

Feldbez.  Satzstellen     Feldformat      Inhalt/Bemerkungen
EF-Nr    von-bis Anzahl  Allg.  Intern    
######   #######     ##     #      ###   ###########
EF1        1-  2      2     C      ALN   Satzart 10
EF2        3- 10      8                  Gebietstand
 EF2U1     3-  6      4     C      ALN     Jahr
 EF2U2     7-  8      2     C      ALN     Monat
 EF2U3     9- 10      2     C      ALN     Tag
EF3       11- 18      8     C      ALN     Amtlicher Regionalschlüssel
 EF3U1    11- 12      2     C      ALN      Land
 EF3U2    13          1     c      ALN      Leer
 EF3U3    14- 15      2     C      ALN      Leer
 EF3U4    16- 18      3     C      ALN      Leer
EF4       19- 22      4     C      ALN     Leer
EF5       23- 72     50     C      ALN     Landbezeichnung
EF6       73-122     50     C      ALN     Sitz der Landesregierung
EF7      123-128      6                    Schlüsselfelder
 EF7U1   123-124      2     C      ALN      Leer
 EF7U2   125-126      2     C      ALN      Leer
 EF7U3   127-128      2     C      ALN      Leer
EF8      129-200     72     C      ALN     Leer
EF9      201-220     20     C      ALN     Frei für landesinterne Angaben

SyntaxError: invalid syntax (2065149292.py, line 1)

## SATZART-20 [Regierungsbezirksdaten]
```Datensatzbeschreibung_GV100AD.pdf```, page 3


Feldbez.  Satzstellen     Feldformat      Inhalt/Bemerkungen
EF-Nr    von-bis Anzahl  Allg.  Intern    
######   #######     ##     #      ###   ###########
EF1        1-  2      2     C      ALN   Satzart 20
EF2        3- 10      8                  Gebietstand
 EF2U1     3-  6      4     C      ALN     Jahr
 EF2U2     7-  8      2     C      ALN     Monat
 EF2U3     9- 10      2     C      ALN     Tag
EF3       11- 18      8     C      ALN     Amtlicher Regionalschlüssel
 EF3U1    11- 12      2     C      ALN      Land
 EF3U2    13          1     c      ALN      Regierungsbezirk
 EF3U3    14- 15      2     C      ALN      Leer
 EF3U4    16- 18      3     C      ALN      Leer
EF4       19- 22      4     C      ALN     Leer
EF5       23- 72     50     C      ALN     Regierungsbezirksbezeichnung
EF6       73-122     50     C      ALN     Sitz der Regierungsbezirks
EF7      123-128      6                    Schlüsselfelder
 EF7U1   123-124      2     C      ALN      Leer
 EF7U2   125-126      2     C      ALN      Leer
 EF7U3   127-128      2     C      ALN      Leer
EF8      129-200     72     C      ALN     Leer
EF9      201-220     20     C      ALN     Frei für landesinterne Angaben

## SATZART-30 [Regionsdaten (nur BaWü)]
```Datensatzbeschreibung_GV100AD.pdf```, page 4


Feldbez.  Satzstellen     Feldformat      Inhalt/Bemerkungen
EF-Nr    von-bis Anzahl  Allg.  Intern    
######   #######     ##     #      ###   ###########
EF1        1-  2      2     C      ALN   Satzart 30
EF2        3- 10      8                  Gebietstand
 EF2U1     3-  6      4     C      ALN     Jahr
 EF2U2     7-  8      2     C      ALN     Monat
 EF2U3     9- 10      2     C      ALN     Tag
EF3       11- 18      8     C      ALN     Amtlicher Regionalschlüssel
 EF3U1    11- 12      2     C      ALN      Land
 EF3U2    13          1     c      ALN      Regierungsbezirk
 EF3U3    14- 15      2     C      ALN      Region (x@). Zur Abbildung der Region wird lediglich Satzstelle 14 benötigt
 EF3U4    16- 18      3     C      ALN      Leer
EF4       19- 22      4     C      ALN     Leer
EF5       23- 72     50     C      ALN     Regionsbezeichnung
EF6       73-122     50     C      ALN     Sitz der Region
EF7      123-128      6                    Schlüsselfelder
 EF7U1   123-124      2     C      ALN      Leer
 EF7U2   125-126      2     C      ALN      Leer
 EF7U3   127-128      2     C      ALN      Leer
EF8      129-200     72     C      ALN     Leer
EF9      201-220     20     C      ALN     Frei für landesinterne Angaben

## SATZART-40 [Kreisdaten (1) -> administrative Gebietseinheiten]
```Datensatzbeschreibung_GV100AD.pdf```, page 5


Feldbez.  Satzstellen     Feldformat      Inhalt/Bemerkungen
EF-Nr    von-bis Anzahl  Allg.  Intern    
######   #######     ##     #      ###   ###########
EF1        1-  2      2     C      ALN   Satzart 40
EF2        3- 10      8                  Gebietstand
 EF2U1     3-  6      4     C      ALN     Jahr
 EF2U2     7-  8      2     C      ALN     Monat
 EF2U3     9- 10      2     C      ALN     Tag
EF3       11- 18      8     C      ALN     Amtlicher Regionalschlüssel
 EF3U1    11- 12      2     C      ALN      Land
 EF3U2    13          1     c      ALN      Regierungsbezirk
 EF3U3    14- 15      2     C      ALN      Kreis
 EF3U4    16- 18      3     C      ALN      Leer
EF4       19- 22      4     C      ALN     Leer
EF5       23- 72     50     C      ALN     Kreisbezeichnung
EF6       73-122     50     C      ALN     Sitz der Kreisverwaltung
EF7      123-128      6                    Schlüsselfelder
 EF7U1   123-124      2     C      ALN      Textkennzeichen
                                            41 - Kreisfreie Stadt
                                            42 - Stadtkreis
                                            43 - Kreis
                                            44 - Landkreis
                                            45 - Regionalverband
 EF7U2   125-126      2     C      ALN      Leer
 EF7U3   127-128      2     C      ALN      Leer
EF8      129-200     72     C      ALN     Leer
EF9      201-220     20     C      ALN     Frei für landesinterne Angaben

## SATZART-50 [Gemeindeverbandsdaten]
```Datensatzbeschreibung_GV100AD.pdf```, page 6


Feldbez.  Satzstellen     Feldformat      Inhalt/Bemerkungen
EF-Nr    von-bis Anzahl  Allg.  Intern    
######   #######     ##     #      ###   ###########
EF1        1-  2      2     C      ALN   Satzart 50
EF2        3- 10      8                  Gebietstand
 EF2U1     3-  6      4     C      ALN     Jahr
 EF2U2     7-  8      2     C      ALN     Monat
 EF2U3     9- 10      2     C      ALN     Tag
EF3       11- 18      8     C      ALN     Amtlicher Regionalschlüssel
 EF3U1    11- 12      2     C      ALN      Land
 EF3U2    13          1     c      ALN      Regierungsbezirk
 EF3U3    14- 15      2     C      ALN      Region (x@). Zur Abbildung der Region wird lediglich Satzstelle 14 benötigt
 EF3U4    16- 18      3     C      ALN      Kreis
EF4       19- 22      4     C      ALN      Leer
EF5       23- 72     50     C      ALN     Gemeindeverband
EF6       73-122     50     C      ALN     Sitz der Gemeindeverbandes
EF7      123-128      6                    Schlüsselfelder
 EF7U1   123-124      2     C      ALN      Textkennzeichen
                                            50 - verbandsfreie Gemeinde
                                            51 - Amt
                                            52 - Samtgemeinde
                                            53 - Verbandsgemeinde
                                            54 - Verwaltungsgemeinschaft
                                            55 - Kirchspielslandgemeinde
                                            56 - Verwaltungsverband
                                            57 - VG Trägermodell
                                            58 - Erfüllende Gemeinde
 EF7U2   125-126      2     C      ALN      Leer
 EF7U3   127-128      2     C      ALN      Leer
EF8      129-200     72     C      ALN     Leer
EF9      201-220     20     C      ALN     Frei für landesinterne Angaben

## SATZART-60 [Gemeindedaten (1) -> administrative Gebietseinheiten]
```Datensatzbeschreibung_GV100AD.pdf```, page 7


Feldbez.  Satzstellen     Feldformat      Inhalt/Bemerkungen
EF-Nr    von-bis Anzahl  Allg.  Intern    
######   #######     ##     #      ###   ###########
EF1        1-  2      2     C      ALN   Satzart 60
EF2        3- 10      8                  Gebietstand
 EF2U1     3-  6      4     C      ALN     Jahr
 EF2U2     7-  8      2     C      ALN     Monat
 EF2U3     9- 10      2     C      ALN     Tag
EF3       11- 18      8     C      ALN     Amtlicher Regionalschlüssel
 EF3U1    11- 12      2     C      ALN      Land
 EF3U2    13          1     c      ALN      Regierungsbezirk
 EF3U3    14- 15      2     C      ALN      Kreis
 EF3U4    16- 18      3     C      ALN      Gemeinde
EF4       19- 22      4     C      ALN     Leer
EF5       23- 72     50     C      ALN     Gemeindeverband
EF6       73-122     50     C      ALN     Leer
EF7      123-128      6                    Schlüsselfelder
 EF7U1   123-124      2     C      ALN      Textkennzeichen
                                            60 - Markt
                                            61 - Kreisfreie Stadt
                                            62 - Stadtkreis
                                            63 - Stadt
                                            64 - Kreisangehörige Gemeinde
                                            65 - gemeindefreies Gebiet, bewohnt
                                            66 - gemeindefreies Gebiet, unbewohnt
                                            67 - große Kreisstadt
 EF7U2   125-126      2     C      ALN      Leer
 EF7U3   127-128      2     C      ALN      Leer
EF8      129-139     11     C NOV11K00     Fläche in ha
EF9      140-150     11     C NOV11K00     Bevölkerung, insgesamt
EF10     151-161     11     C NOV11K00     Bevölkerung, männlich
EF11     162-165      4     C      ALN     Leer
EF12     166-175     10                    Neue Postleitzahl
 EF12U1  166-170      5     C      ALN      PLZ der Gemeinde (bei mehreren Postleitzahlen - PLZ des Verwaltungssitzes)
 EF12U2  171-175      6     C      ALN      Kennzeichnung, ob PLZ eindeutig (leer = Gemeinde hat nur eine PLZ, sonst = Gemeinde hat mehrere PLZ)
EF13     176-177      2     C      ALN     LEER
EF14     178-181      4     C      ALN     Finanzamtsbezirk
EF15     182-185      5                    Gerichtsbarkeit
 EF15U1  182-183      2     C      ALN      Oberlandesgerichtsbezirk
 EF15U2  184          1     C      ALN      Landgerichtsbezirk
 EF15U3  185          1     C      ALN      Amtsgerichtsbezirk
EF16     186-190      5     C      ALN     Arbeitsagenturbezirk
EF17     191-196      6                    Bundestagswahlkreise
 EF17U1  191-193      3     C      ALN      Bundestagswahlkreis
 EF17U2  194-196      3     C      ALN      Bundestagswahlkreis
EF18     197-200      2     C      ALN    Leer
EF19     201-220     20     C      ALN    Frei für landesinterne Angaben

# 2. PROCESSING [PARSING ```GV_100AD_DDMMYYYY.txt```]

#### SATZART-10 [Landdaten]
#### SATZART-20 [Regierungsbezirksdaten]
#### SATZART-30 [Regionsdaten (nur BaWü)]
#### SATZART-40 [Kreisdaten (1) -> administrative Gebietseinheiten]
#### SATZART-50 [Gemeindeverbandsdaten]
#### SATZART-60 [Gemeindedaten (1) -> administrative Gebietseinheiten]

## 2.1. Satzarten [10,20,30,40,50]

### 2.1.1. PARSE FILE ```df```

In [2]:
filename = 'GV100AD_31102024'

widths=[
     2, # EF1,   1-  2
     8, # EF2,   3- 10
     8, # EF3,  11- 18
     4, # EF4,  19- 22
    50, # EF5,  23- 72
    50, # EF6,  73-122
     6, # EF7, 123-128
    72, # EF8, 129-200
    20, # EF9, 200-220
]

col_names = [
    'EF1_Satzart',
    'EF2_Gebietstand',
    'EF3_ARS',
    'EF4_Verband',
    'EF5_Verbandsbezeichnung',
    'EF6_Sitz_des_Verbandes',
    'EF7_Schlüsselfelder',
    'EF8_Leer',
    'EF9_Frei für landesinterne Angaben',
]

In [3]:
path_GV100_read= f'GV_GemeindeVerzeichnis//{filename}.txt'
path_GV100_save= f'GV_GemeindeVerzeichnis//{filename}_df.csv'
path_GV100_read

'GV_GemeindeVerzeichnis//GV100AD_31102024.txt'

In [9]:
import f_gemeinde_verzeichnis

In [10]:
df = f_gemeinde_verzeichnis.parse_GV100(path_read=path_GV100_read, widths=widths, col_names=col_names)

NameError: name 'f_deutschland_2022' is not defined

In [946]:
df = pd.read_fwf(
    filepath_or_buffer= 'GV_GemeindeVerzeichnis/GV100AD_31102024.txt', 
    widths=widths, 
    header=None,
    names=col_names,
    dtype={'EF3_ARS': str}
)  # Specify column widths

df.replace({
    'Ã¼': 'ü',
    'Ã¶': 'ö',
    'ÃŸ': 'ß',
    'Ã¤': 'ä',
}, inplace=True)

## ADDING column 'BL_nr' and set column type to int
df[col_BL_number] = df['EF3_ARS'].str.slice(0, 2)
df[col_BL_number] = df[col_BL_number].astype('int')
# df['EF4_Verband'] = df['EF4_Verband'].fillna(0).astype('int')

## ADDING column 'BL_name'
df[col_BL_name] = df[col_BL_number].map(f_deutschland_2022.dict_id_bundeslaender)

print(f'df.shape={df.shape}')

if is_file_saved:
    df.to_csv(path_file_saved)

df

df.shape=(16012, 11)

,EF1_Satzart,EF2_Gebietstand,EF3_ARS,EF4_Verband,EF5_Verbandsbezeichnung,EF6_Sitz_des_Verbandes,EF7_Schlüsselfelder,EF8_Leer,EF9_Frei für landesinterne Angaben,BL_nr,BL_name
0,10,20241031,01,NaN,Schleswig-Holstein,Kiel,NaN,NaN,NaN,1,Schleswig-Holstein
1,40,20241031,01001,NaN,"Flensburg, Stadt",Flensburg,41.0,NaN,NaN,1,Schleswig-Holstein
2,50,20241031,01001,0.0,"Flensburg, Stadt",NaN,50.0,NaN,NaN,1,Schleswig-Holstein
3,60,20241031,01001000,0.0,"Flensburg, Stadt",NaN,61.0,000000056730000009266700000045905 24937****...,NaN,1,Schleswig-Holstein
4,40,20241031,01002,NaN,"Kiel, Landeshauptstadt",Kiel,41.0,NaN,NaN,1,Schleswig-Holstein
...,...,...,...,...,...,...,...,...,...,...,...
16007,60,20241031,16077044,5005.0,Starkenberg,NaN,64.0,000000026420000000180200000000905 04617 ...,NaN,16,Thüringen
16008,60,20241031,16077047,5009.0,Thonhausen,NaN,64.0,000000009420000000050100000000257 04626 ...,NaN,16,Thüringen
16009,60,20241031,16077048,5004.0,Treben,NaN,64.0,000000010000000000117400000000567 04617 ...,NaN,16,Thüringen
16010,60,20241031,16077049,5009.0,Vollmershain,NaN,64.0,000000005060000000030400000000150 04626 ...,NaN,16,Thüringen
16011,60,20241031,16077052,5004.0,Windischleuba,NaN,64.0,000000020730000000186100000000914 04603****...,NaN,16,Thüringen

### 2.1.2. SUM FILE ```df_adm_sum```

In [947]:
df_adm_sum = df.groupby([col_BL_name])['EF1_Satzart'].count().to_frame()
print(f'sum(df_adm_sum)= {df_adm_sum.sum()}')
df_adm_sum

sum(df_adm_sum)= EF1_Satzart    16012
dtype: int64

                        EF1_Satzart
BL_name
Baden-Württemberg              1626
Bayern                         3887
Berlin                            4
Brandenburg                     625
Bremen                            7
Hamburg                           4
Hessen                          880
Mecklenburg-Vorpommern          851
Niedersachsen                  1442
Nordrhein-Westfalen             851
Rheinland-Pfalz                2513
Saarland                        113
Sachsen                         744
Sachsen-Anhalt                  355
Schleswig-Holstein             1293
Thüringen                       817

## 2.2. Satzarten [60]

### 2.2.1. PARSE FILE in ```df_60```

In [986]:
import f_gemeinde_verzeichnis

In [987]:
width_60 = [
    11, #11 Fläche in ha
    11, #11 Bevölkerung, insgesamt
    11, #11 Bevölkerung, männlich
    4,  #4  Leer
    10, #10 Neue Postleitzahl
    2,  #2  Leer
    4,  #4  Finanzamtsbezirk
    5,  #4  Gerichtsbarkeit
    5,  #5  Arbeitsagenturbezirk
    6,  #6  Bundestagswahlkreise
    4   #4  Leer
]
df_60 = parse_60(df=df, width_60=width_60)

C:\Users\gujua\AppData\Local\Temp\ipykernel_15356\2471914544.py:40: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_60[col_REGBEZ_number] = df_60['EF3_ARS'].str.slice(2, 3).astype('int')
C:\Users\gujua\AppData\Local\Temp\ipykernel_15356\2471914544.py:44: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_60[col_KREIS_number] = df_60['EF3_ARS'].str.slice(3, 5).astype('int')
C:\Users\gujua\AppData\Local\Temp\ipykernel_15356\2471914544.py:47: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_60[col_GEMEINDE_number] = df_60['EF3_ARS'].str.slice(5, 8).astype('int')
C:\Users\gujua\AppData\Local\Temp\ipykernel_15356\2471914544.py:50: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_60[col_VERBANDGEMEINDE_number] = df_60[col_VERBANDGEMEINDE_number].astype('int')
C:\Users\gujua\AppData\Local\Temp\ipykernel_15356\2471914544.py:62: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_60['EF7_Schlüsselfelder'] = df_60['EF7_Schlüsselfelder'].astype('int')
C:\Users\gujua\AppData\Local\Temp\ipykernel_15356\2471914544.py:63: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_60['GEM_TYPE'] = df_60['EF7_Schlüsselfelder'].map(dict_keyField)
C:\Users\gujua\AppData\Local\Temp\ipykernel_15356\2471914544.py:69: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_60[field] = df_60.EF8_Leer.str[pos_start:pos_end]
C:\Users\gujua\AppData\Local\Temp\ipykernel_15356\2471914544.py:71: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_60[field] = df_60[field].fillna(0)
C:\Users\gujua\AppData\Local\Temp\ipykernel_15356\2471914544.py:72: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_60[field] = df_60[field].astype(field_type)
C:\Users\gujua\AppData\Local\Temp\ipykernel_15356\2471914544.py:69: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_60[field] = df_60.EF8_Leer.str[pos_start:pos_end]
C:\Users\gujua\AppData\Local\Temp\ipykernel_15356\2471914544.py:71: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_60[field] = df_60[field].fillna(0)
C:\Users\gujua\AppData\Local\Temp\ipykernel_15356\2471914544.py:72: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_60[field] = df_60[field].astype(field_type)
C:\Users\gujua\AppData\Local\Temp\ipykernel_15356\2471914544.py:69: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_60[field] = df_60.EF8_Leer.str[pos_start:pos_end]
C:\Users\gujua\AppData\Local\Temp\ipykernel_15356\2471914544.py:71: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_60[field] = df_60[field].fillna(0)
C:\Users\gujua\AppData\Local\Temp\ipykernel_15356\2471914544.py:72: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_60[field] = df_60[field].astype(field_type)
C:\Users\gujua\AppData\Local\Temp\ipykernel_15356\2471914544.py:69: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_60[field] = df_60.EF8_Leer.str[pos_start:pos_end]
C:\Users\gujua\AppData\Local\Temp\ipykernel_15356\2471914544.py:69: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_60[field] = df_60.EF8_Leer.str[pos_start:pos_end]
C:\Users\gujua\AppData\Local\Temp\ipykernel_15356\2471914544.py:69: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_60[field] = df_60.EF8_Leer.str[pos_start:pos_end]
C:\Users\gujua\AppData\Local\Temp\ipykernel_15356\2471914544.py:69: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_60[field] = df_60.EF8_Leer.str[pos_start:pos_end]
C:\Users\gujua\AppData\Local\Temp\ipykernel_15356\2471914544.py:69: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_60[field] = df_60.EF8_Leer.str[pos_start:pos_end]
C:\Users\gujua\AppData\Local\Temp\ipykernel_15356\2471914544.py:69: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_60[field] = df_60.EF8_Leer.str[pos_start:pos_end]
C:\Users\gujua\AppData\Local\Temp\ipykernel_15356\2471914544.py:69: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_60[field] = df_60.EF8_Leer.str[pos_start:pos_end]

sum(df_60)= (10959, 25)

C:\Users\gujua\AppData\Local\Temp\ipykernel_15356\2471914544.py:84: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_60[col] = pd.to_numeric(df_60[col], errors='coerce')
C:\Users\gujua\AppData\Local\Temp\ipykernel_15356\2471914544.py:85: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_60[col] = df_60[col].fillna(0).astype('int')
C:\Users\gujua\AppData\Local\Temp\ipykernel_15356\2471914544.py:84: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_60[col] = pd.to_numeric(df_60[col], errors='coerce')
C:\Users\gujua\AppData\Local\Temp\ipykernel_15356\2471914544.py:85: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_60[col] = df_60[col].fillna(0).astype('int')
C:\Users\gujua\AppData\Local\Temp\ipykernel_15356\2471914544.py:84: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_60[col] = pd.to_numeric(df_60[col], errors='coerce')
C:\Users\gujua\AppData\Local\Temp\ipykernel_15356\2471914544.py:85: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_60[col] = df_60[col].fillna(0).astype('int')
C:\Users\gujua\AppData\Local\Temp\ipykernel_15356\2471914544.py:84: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_60[col] = pd.to_numeric(df_60[col], errors='coerce')
C:\Users\gujua\AppData\Local\Temp\ipykernel_15356\2471914544.py:85: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_60[col] = df_60[col].fillna(0).astype('int')

## 2.2. SUMMARISE FILE for [Gemeinde, Bevölkerung,Fläche] in ```df_sum```
- SATZARTEN (```df_adm_sum```)

In [967]:
import f_gemeinde_verzeichnis

In [968]:
width_60 = [
    11, #11 Fläche in ha
    11, #11 Bevölkerung, insgesamt
    11, #11 Bevölkerung, männlich
    4,  #4  Leer
    10, #10 Neue Postleitzahl
    2,  #2  Leer
    4,  #4  Finanzamtsbezirk
    4,  #4  Gerichtsbarkeit
    5,  #5  Arbeitsagenturbezirk
    6,  #6  Bundestagswahlkreise
    4   #4  Leer
]
df_60 = parse_60(df=df, width_60=width_60)

df_ade1 = process_sa60(df=df_60, ADE_level=1)
print(f'shape(df_ade1)=[{df_ade1.shape}]')
# df_ade1

df_ade2 = process_sa60(df=df_60, ADE_level=2)
print(f'shape(df_ade2)=[{df_ade2.shape}]')
df_ade3 = process_sa60(df=df_60, ADE_level=3)
print(f'shape(df_ade3)=[{df_ade3.shape}]')
df_ade4 = process_sa60(df=df_60, ADE_level=4)
print(f'shape(df_ade4)=[{df_ade4.shape}]')
df_ade5 = process_sa60(df=df_60, ADE_level=5)
print(f'shape(df_ade5)=[{df_ade5.shape}]')
df_ade6 = process_sa60(df=df_60, ADE_level=6)
print(f'shape(df_ade6)=[{df_ade6.shape}]')

C:\Users\gujua\AppData\Local\Temp\ipykernel_15356\2471914544.py:40: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_60[col_REGBEZ_number] = df_60['EF3_ARS'].str.slice(2, 3).astype('int')
C:\Users\gujua\AppData\Local\Temp\ipykernel_15356\2471914544.py:44: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_60[col_KREIS_number] = df_60['EF3_ARS'].str.slice(3, 5).astype('int')
C:\Users\gujua\AppData\Local\Temp\ipykernel_15356\2471914544.py:47: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_60[col_GEMEINDE_number] = df_60['EF3_ARS'].str.slice(5, 8).astype('int')
C:\Users\gujua\AppData\Local\Temp\ipykernel_15356\2471914544.py:50: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_60[col_VERBANDGEMEINDE_number] = df_60[col_VERBANDGEMEINDE_number].astype('int')
C:\Users\gujua\AppData\Local\Temp\ipykernel_15356\2471914544.py:62: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_60['EF7_Schlüsselfelder'] = df_60['EF7_Schlüsselfelder'].astype('int')
C:\Users\gujua\AppData\Local\Temp\ipykernel_15356\2471914544.py:63: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_60['GEM_TYPE'] = df_60['EF7_Schlüsselfelder'].map(dict_keyField)
C:\Users\gujua\AppData\Local\Temp\ipykernel_15356\2471914544.py:69: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_60[field] = df_60.EF8_Leer.str[pos_start:pos_end]
C:\Users\gujua\AppData\Local\Temp\ipykernel_15356\2471914544.py:71: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_60[field] = df_60[field].fillna(0)
C:\Users\gujua\AppData\Local\Temp\ipykernel_15356\2471914544.py:72: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_60[field] = df_60[field].astype(field_type)
C:\Users\gujua\AppData\Local\Temp\ipykernel_15356\2471914544.py:69: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_60[field] = df_60.EF8_Leer.str[pos_start:pos_end]
C:\Users\gujua\AppData\Local\Temp\ipykernel_15356\2471914544.py:71: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_60[field] = df_60[field].fillna(0)
C:\Users\gujua\AppData\Local\Temp\ipykernel_15356\2471914544.py:72: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_60[field] = df_60[field].astype(field_type)
C:\Users\gujua\AppData\Local\Temp\ipykernel_15356\2471914544.py:69: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_60[field] = df_60.EF8_Leer.str[pos_start:pos_end]
C:\Users\gujua\AppData\Local\Temp\ipykernel_15356\2471914544.py:71: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_60[field] = df_60[field].fillna(0)
C:\Users\gujua\AppData\Local\Temp\ipykernel_15356\2471914544.py:72: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_60[field] = df_60[field].astype(field_type)
C:\Users\gujua\AppData\Local\Temp\ipykernel_15356\2471914544.py:69: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_60[field] = df_60.EF8_Leer.str[pos_start:pos_end]
C:\Users\gujua\AppData\Local\Temp\ipykernel_15356\2471914544.py:69: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_60[field] = df_60.EF8_Leer.str[pos_start:pos_end]
C:\Users\gujua\AppData\Local\Temp\ipykernel_15356\2471914544.py:69: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_60[field] = df_60.EF8_Leer.str[pos_start:pos_end]
C:\Users\gujua\AppData\Local\Temp\ipykernel_15356\2471914544.py:69: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_60[field] = df_60.EF8_Leer.str[pos_start:pos_end]
C:\Users\gujua\AppData\Local\Temp\ipykernel_15356\2471914544.py:69: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_60[field] = df_60.EF8_Leer.str[pos_start:pos_end]
C:\Users\gujua\AppData\Local\Temp\ipykernel_15356\2471914544.py:69: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_60[field] = df_60.EF8_Leer.str[pos_start:pos_end]
C:\Users\gujua\AppData\Local\Temp\ipykernel_15356\2471914544.py:69: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_60[field] = df_60.EF8_Leer.str[pos_start:pos_end]
C:\Users\gujua\AppData\Local\Temp\ipykernel_15356\2471914544.py:84: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_60[col] = pd.to_numeric(df_60[col], errors='coerce')
C:\Users\gujua\AppData\Local\Temp\ipykernel_15356\2471914544.py:85: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_60[col] = df_60[col].fillna(0).astype('int')
C:\Users\gujua\AppData\Local\Temp\ipykernel_15356\2471914544.py:84: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_60[col] = pd.to_numeric(df_60[col], errors='coerce')
C:\Users\gujua\AppData\Local\Temp\ipykernel_15356\2471914544.py:85: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_60[col] = df_60[col].fillna(0).astype('int')
C:\Users\gujua\AppData\Local\Temp\ipykernel_15356\2471914544.py:84: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_60[col] = pd.to_numeric(df_60[col], errors='coerce')
C:\Users\gujua\AppData\Local\Temp\ipykernel_15356\2471914544.py:85: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_60[col] = df_60[col].fillna(0).astype('int')
C:\Users\gujua\AppData\Local\Temp\ipykernel_15356\2471914544.py:84: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_60[col] = pd.to_numeric(df_60[col], errors='coerce')
C:\Users\gujua\AppData\Local\Temp\ipykernel_15356\2471914544.py:85: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_60[col] = df_60[col].fillna(0).astype('int')

sum(df_60)= (10959, 25)
shape(df_ade1)=[(1, 32)]
shape(df_ade2)=[(16, 33)]
shape(df_ade3)=[(39, 34)]
shape(df_ade4)=[(402, 35)]
shape(df_ade5)=[(4596, 36)]
shape(df_ade6)=[(10959, 39)]

## TESTS

### BREMEN (04)

In [969]:
## BREMEN
l_cols = [
    'Fläche in ha',
    'Bevölkerung, insgesamt',
    'Bevölkerung, männlich',
    'Neue Postleitzahl',
    'Finanzamtsbezirk','Gerichtsbarkeit','Arbeitsagenturbezirk',
    'Bundestagswahlkreise'
]
df_ade4[df_ade4['ADE2']=='04'][l_cols]

   Fläche in ha                   Bevölkerung, insgesamt                      \
            sum   median     mean                    sum    median      mean
61        31820  31820.0  31820.0                 577026  577026.0  577026.0
62        10141  10141.0  10141.0                 114677  114677.0  114677.0

   Bevölkerung, männlich                     Neue Postleitzahl                \
                     sum    median      mean           nunique        unique
61                285270  285270.0  285270.0                 1  [28195*****]
62                 56716   56716.0   56716.0                 1  [27576*****]

   Finanzamtsbezirk         Gerichtsbarkeit         Arbeitsagenturbezirk  \
            nunique  unique         nunique  unique              nunique
61                1  [2471]               1  [1101]                    1
62                1  [2475]               1  [1102]                    1

            Bundestagswahlkreise
     unique              nunique   unique
61  [21401]                    1  [54055]
62  [21419]                    1     [55]

In [970]:
# BREMEN
df_60[df_60['BL_nr']==4]['EF8_Leer'].values#[l_cols]
# 000000318200000057702600000285270    28195*****  2471110121401054055
  # 00000031820, 00000577026, 00000285270,    ,28195*****,  ,2471,1101,21401,054055
# 000000101410000011467700000056716    27576*****  2475110221419055
  # 00000010141, 00000114677, 00000056716,    ,27576*****,  ,2475,1102,21419,055

# 11, #11 Fläche in ha            [00000031820, 00000010141] YES
# 11, #11 Bevölkerung, insgesamt  [00000577026, 00000114677] YES
# 11, #11 Bevölkerung, männlich   [00000285270, 00000056716] YES
# 4,  #4 Leer                     [     '    ',      '    '] YES
# 10, #10 Neue Postleitzahl       [ 28195*****,  27576*****] YES
# 2,  #2 Leer                     [       '  ',        '  '] YES
# 4,  #4 Finanzamtsbezirk         [       2471,        2475] YES
# 5,  #4 Gerichtsbarkeit          [       1101,        1102] YES
# 5,  #5 Arbeitsagenturbezirk     [      21401,       21419] YES
# 6,  #6 Bundestagswahlkreise     [     054055,      055   ] YES
# 4   # Leer

array(['000000318200000057702600000285270    28195*****  2471110121401054055',
       '000000101410000011467700000056716    27576*****  2475110221419055'],
      dtype=object)

### HAMBURG (02)

In [971]:
## HAMBURG
l_cols = [
    'Fläche in ha',
    'Bevölkerung, insgesamt',
    'Bevölkerung, männlich',
    'Neue Postleitzahl',
    'Finanzamtsbezirk','Gerichtsbarkeit','Arbeitsagenturbezirk',
    'Bundestagswahlkreise'
]
df_ade4[df_ade4['ADE2']=='02'][l_cols]

   Fläche in ha                   Bevölkerung, insgesamt             \
            sum   median     mean                    sum     median
15        75509  75509.0  75509.0                1910160  1910160.0

              Bevölkerung, männlich                     Neue Postleitzahl  \
         mean                   sum    median      mean           nunique
15  1910160.0                936740  936740.0  936740.0                 1

                 Finanzamtsbezirk         Gerichtsbarkeit          \
          unique          nunique  unique         nunique  unique
15  [20038*****]                1  [2202]               1  [1100]

   Arbeitsagenturbezirk          Bundestagswahlkreise
                nunique   unique              nunique   unique
15                    1  [12301]                    1  [18023]

In [972]:
# HAMBURG
df_60[df_60['BL_nr']==2]['EF8_Leer'].values
# 000000755090000191016000000936740    20038*****  2202110012301018023
  # 00000075509, 00001910160, 00000936740,    , 20038*****,   , 2202, 1100, 12301, 018023

array(['000000755090000191016000000936740    20038*****  2202110012301018023'],
      dtype=object)

# SAVE DFs

In [974]:
df_ade1.head(1)
# df_ade1.to_csv('df_ade1.csv')

            ARS BL_name ADE2_LAND        BEZ_NR        KREIS_NR         \
                             mean  count   mean  count     mean  count
0  000000000000      60      7.96  10959   2.23  10959    53.51  10959

  EF4_Verband         ... Neue Postleitzahl  \
         mean  count  ...           nunique
0     3812.86  10959  ...              6678

                                                     Finanzamtsbezirk  \
                                              unique          nunique
0  [24937*****, 24103*****, 23539*****, 24534****...              460

                                                     Gerichtsbarkeit  \
                                              unique         nunique
0  [2115, 2119, 2122, 2124, 2123, 2116, 2127, 212...             391

                                                     Arbeitsagenturbezirk  \
                                              unique              nunique
0  [1112, 1517, 1721, 1519, 1319, 1725, 1726, 172...                  706

                                                     Bundestagswahlkreise  \
                                              unique              nunique
0  [11901, 13101, 13501, 13901, 12701, 12705, 127...                  272


                                              unique
0  [1, 5, 11, 6, 3, 2, 10, 9, 7, 4, 8, 18023, 50,...

[1 rows x 32 columns]

In [975]:
df_ade2.head()
# df_ade2.to_csv('df_ade2.csv')

            ARS              BL_name ADE2 ADE2_LAND       BEZ_NR        \
                                               mean count   mean count
0  010000000000   Schleswig-Holstein   01       1.0  1106   0.00  1106
1  020000000000              Hamburg   02       2.0     1   0.00     1
2  030000000000        Niedersachsen   03       3.0   964   2.68   964
3  040000000000               Bremen   04       4.0     2   0.00     2
4  050000000000  Nordrhein-Westfalen   05       5.0   396   5.03   396

  KREIS_NR       EF4_Verband  ... Neue Postleitzahl  \
      mean count        mean  ...           nunique
0    56.50  1106     5075.98  ...               467
1     0.00     1        0.00  ...                 1
2    54.80   964     3895.15  ...               674
3    11.50     2        0.00  ...                 2
4    61.66   396       26.45  ...               394

                                                     Finanzamtsbezirk  \
                                              unique          nunique
0  [24937*****, 24103*****, 23539*****, 24534****...               21
1                                       [20038*****]                1
2  [38100*****, 38226*****, 38440*****, 38528    ...               50
3                           [28195*****, 27576*****]                2
4  [40213*****, 47051*****, 45121*****, 47798****...               85

                                                     Gerichtsbarkeit  \
                                              unique         nunique
0  [2115, 2119, 2122, 2124, 2123, 2116, 2127, 212...              22
1                                             [2202]               1
2  [2314, 2351, 2319, 2321, 2328, 2335, 2338, 231...              80
3                                       [2471, 2475]               2
4  [5103, 5107, 5111, 5117, 5121, 5120, 5123, 512...             123

                                                     Arbeitsagenturbezirk  \
                                              unique              nunique
0  [1112, 1517, 1721, 1519, 1319, 1725, 1726, 172...                   32
1                                             [1100]                    1
2  [1103, 1108, 1117, 2407, 1104, 1111, 1116, 110...                   87
3                                       [1101, 1102]                    2
4  [1111, 1212, 4513, 1412, 1514, 1215, 1216, 161...                  124

                                                     Bundestagswahlkreise  \
                                              unique              nunique
0  [11901, 13101, 13501, 13901, 12701, 12705, 127...                   11
1                                            [12301]                    1
2  [21101, 21109, 24117, 24105, 0, 21115, 21121, ...                   29
3                                     [21401, 21419]                    2
4  [33701, 34101, 34301, 36101, 36501, 37105, 371...                   59


                                              unique
0                [1, 5, 11, 6, 3, 2, 10, 9, 7, 4, 8]
1                                            [18023]
2  [50, 49, 51, 45, 52, 46, 53, 41042, 47, 43, 33...
3                                        [54055, 55]
4  [105106, 114115, 117119, 109113, 108, 117, 116...

[5 rows x 33 columns]

In [978]:
df_ade3.head()
# df_ade3.to_csv('df_ade3.csv')

            ARS             BL_name ADE2 ADE3 ADE2_LAND       BEZ_NR        \
                                                   mean count   mean count
0  010000000000  Schleswig-Holstein   01    0       1.0  1106    0.0  1106
1  020000000000             Hamburg   02    0       2.0     1    0.0     1
2  031000000000       Niedersachsen   03    1       3.0   175    1.0   175
3  032000000000       Niedersachsen   03    2       3.0   207    2.0   207
4  033000000000       Niedersachsen   03    3       3.0   333    3.0   333

  KREIS_NR        ... Neue Postleitzahl  \
      mean count  ...           nunique
0    56.50  1106  ...               467
1     0.00     1  ...                 1
2    54.47   175  ...               127
3    53.04   207  ...               156
4    55.81   333  ...               228

                                                     Finanzamtsbezirk  \
                                              unique          nunique
0  [24937*****, 24103*****, 23539*****, 24534****...               21
1                                       [20038*****]                1
2  [38100*****, 38226*****, 38440*****, 38528    ...                9
3  [30159*****, 30890     , 31303     , 30938    ...               11
4  [29352     , 29353     , 29355     , 29303    ...               13

                                                     Gerichtsbarkeit  \
                                              unique         nunique
0  [2115, 2119, 2122, 2124, 2123, 2116, 2127, 212...              22
1                                             [2202]               1
2  [2314, 2351, 2319, 2321, 2328, 2335, 2338, 231...              18
3  [2324, 2323, 2316, 2327, 2334, 2345, 2346, 232...              20
4  [2317, 2318, 2349, 2315, 2350, 2347, 2333, 233...              19

                                                     Arbeitsagenturbezirk  \
                                              unique              nunique
0  [1112, 1517, 1721, 1519, 1319, 1725, 1726, 172...                   32
1                                             [1100]                    1
2  [1103, 1108, 1117, 2407, 1104, 1111, 1116, 110...                   18
3  [2305, 2308, 2403, 2303, 2306, 2410, 2307, 271...                   25
4  [2503, 2611, 2603, 2608, 2613, 2511, 2504, 250...                   20

                                                     Bundestagswahlkreise  \
                                              unique              nunique
0  [11901, 13101, 13501, 13901, 12701, 12705, 127...                   11
1                                            [12301]                    1
2  [21101, 21109, 24117, 24105, 0, 21115, 21121, ...                    7
3  [23701, 23705, 23725, 23727, 23709, 23713, 237...                    7
4  [22101, 22109, 26717, 26713, 26729, 25109, 251...                    7


                                unique
0  [1, 5, 11, 6, 3, 2, 10, 9, 7, 4, 8]
1                              [18023]
2         [50, 49, 51, 45, 52, 46, 53]
3      [41042, 47, 43, 33, 46, 48, 40]
4         [44, 29, 36, 37, 34, 35, 30]

[5 rows x 34 columns]

In [983]:
# df_ade4.to_csv('df_ade4.csv')
df_ade4#.head()

              ARS             BL_name ADE2 ADE3 ADE4 ADE2_LAND       BEZ_NR  \
                                                          mean count   mean
0    010010000000  Schleswig-Holstein   01    0   01       1.0     1    0.0
1    010020000000  Schleswig-Holstein   01    0   02       1.0     1    0.0
2    010030000000  Schleswig-Holstein   01    0   03       1.0     1    0.0
3    010040000000  Schleswig-Holstein   01    0   04       1.0     1    0.0
4    010510000000  Schleswig-Holstein   01    0   51       1.0   116    0.0
..            ...                 ...  ...  ...  ...       ...   ...    ...
397  160730000000           Thüringen   16    0   73      16.0    26    0.0
398  160740000000           Thüringen   16    0   74      16.0    91    0.0
399  160750000000           Thüringen   16    0   75      16.0    59    0.0
400  160760000000           Thüringen   16    0   76      16.0    42    0.0
401  160770000000           Thüringen   16    0   77      16.0    30    0.0

          KREIS_NR  ... Neue Postleitzahl  \
    count     mean  ...           nunique
0       1      1.0  ...                 1
1       1      2.0  ...                 1
2       1      3.0  ...                 1
3       1      4.0  ...                 1
4     116     51.0  ...                35
..    ...      ...  ...               ...
397    26     73.0  ...                14
398    91     74.0  ...                13
399    59     75.0  ...                18
400    42     76.0  ...                16
401    30     77.0  ...                10

                                                       Finanzamtsbezirk  \
                                                unique          nunique
0                                         [24937*****]                1
1                                         [24103*****]                1
2                                         [23539*****]                1
3                                         [24534*****]                1
4    [25767     , 25715     , 25704     , 25791    ...                2
..                                                 ...              ...
397  [07426     , 07338     , 07422     , 07426****...                1
398  [07646*****, 07768     , 07639     , 07646    ...                1
399  [07381     , 07907     , 07819     , 07924    ...                1
400  [07586     , 07554*****, 07589     , 07580****...                2
401  [04600     , 04626     , 04617     , 04603****...                1

                  Gerichtsbarkeit               Arbeitsagenturbezirk  \
           unique         nunique        unique              nunique
0          [2115]               1        [1112]                    1
1          [2119]               1        [1517]                    1
2          [2122]               1        [1721]                    1
3          [2124]               1        [1519]                    1
4    [2123, 2116]               1        [1319]                    3
..            ...             ...           ...                  ...
397        [4165]               2  [1210, 1211]                    1
398        [4162]               2  [1214, 1206]                    2
399        [4165]               2  [1209, 1208]                    2
400  [4161, 4166]               2  [1203, 1205]                    2
401        [4166]               1        [1201]                    1

                           Bundestagswahlkreise
                    unique              nunique  unique
0                  [11901]                    1     [1]
1                  [13101]                    1     [5]
2                  [13501]                    1    [11]
3                  [13901]                    1     [6]
4    [12701, 12705, 12713]                    2  [3, 2]
..                     ...                  ...     ...
397                 [9421]                    1   [194]
398           [9415, 9419]                    1   [194]
399           [9411, 9413]                    1   [194]
400           [9401, 9405]                    1   [193]
401                 [9403]                    1   [193]

[402 rows x 35 columns]

In [982]:
# df_ade5.to_csv('df_ade5.csv')
df_ade5#.head()

               ARS             BL_name ADE2 ADE3 ADE4  ADE5 ADE2_LAND        \
                                                                 mean count
0     010010000000  Schleswig-Holstein   01    0   01  0000       1.0     1
1     010020000000  Schleswig-Holstein   01    0   02  0000       1.0     1
2     010030000000  Schleswig-Holstein   01    0   03  0000       1.0     1
3     010040000000  Schleswig-Holstein   01    0   04  0000       1.0     1
4     010510011000  Schleswig-Holstein   01    0   51  0011       1.0     1
...            ...                 ...  ...  ...  ...   ...       ...   ...
4591  160775005000           Thüringen   16    0   77  5005      16.0     8
4592  160775009000           Thüringen   16    0   77  5009      16.0     6
4593  160775050000           Thüringen   16    0   77  5050      16.0     3
4594  160775051000           Thüringen   16    0   77  5051      16.0     3
4595  160775052000           Thüringen   16    0   77  5052      16.0     2

     BEZ_NR        ... Neue Postleitzahl  \
       mean count  ...           nunique
0       0.0     1  ...                 1
1       0.0     1  ...                 1
2       0.0     1  ...                 1
3       0.0     1  ...                 1
4       0.0     1  ...                 1
...     ...   ...  ...               ...
4591    0.0     8  ...                 3
4592    0.0     6  ...                 1
4593    0.0     3  ...                 2
4594    0.0     3  ...                 2
4595    0.0     2  ...                 1

                                           Finanzamtsbezirk          \
                                    unique          nunique  unique
0                             [24937*****]                1  [2115]
1                             [24103*****]                1  [2119]
2                             [23539*****]                1  [2122]
3                             [24534*****]                1  [2124]
4                             [25541     ]                1  [2123]
...                                    ...              ...     ...
4591  [04603*****, 04626*****, 04617     ]                1  [4166]
4592                          [04626     ]                1  [4166]
4593              [04639     , 04626*****]                1  [4166]
4594              [04618*****, 04603     ]                1  [4166]
4595                          [04626     ]                1  [4166]

     Gerichtsbarkeit         Arbeitsagenturbezirk           \
             nunique  unique              nunique   unique
0                  1  [1112]                    1  [11901]
1                  1  [1517]                    1  [13101]
2                  1  [1721]                    1  [13501]
3                  1  [1519]                    1  [13901]
4                  1  [1319]                    1  [12705]
...              ...     ...                  ...      ...
4591               1  [1201]                    1   [9403]
4592               1  [1201]                    1   [9403]
4593               1  [1201]                    1   [9403]
4594               1  [1201]                    1   [9403]
4595               1  [1201]                    1   [9403]

     Bundestagswahlkreise
                  nunique unique
0                       1    [1]
1                       1    [5]
2                       1   [11]
3                       1    [6]
4                       1    [3]
...                   ...    ...
4591                    1  [193]
4592                    1  [193]
4593                    1  [193]
4594                    1  [193]
4595                    1  [193]

[4596 rows x 36 columns]

In [984]:
df_ade6.to_csv('df_ade6.csv')
df_ade6#.head()

                ARS             BL_name ADE2 ADE3 ADE4  ADE5 ADE6  \

0      010010000000  Schleswig-Holstein   01    0   01  0000  000
1      010020000000  Schleswig-Holstein   01    0   02  0000  000
2      010030000000  Schleswig-Holstein   01    0   03  0000  000
3      010040000000  Schleswig-Holstein   01    0   04  0000  000
4      010510011011  Schleswig-Holstein   01    0   51  0011  011
...             ...                 ...  ...  ...  ...   ...  ...
10954  160775051011           Thüringen   16    0   77  5051  011
10955  160775051023           Thüringen   16    0   77  5051  023
10956  160775051036           Thüringen   16    0   77  5051  036
10957  160775052003           Thüringen   16    0   77  5052  003
10958  160775052043           Thüringen   16    0   77  5052  043

      EF5_Verbandsbezeichnung                  GEM_TYPE ADE2_LAND  ...  \
                                                             mean  ...
0            Flensburg, Stadt          Kreisfreie Stadt       1.0  ...
1      Kiel, Landeshauptstadt          Kreisfreie Stadt       1.0  ...
2          Lübeck, Hansestadt          Kreisfreie Stadt       1.0  ...
3           Neumünster, Stadt          Kreisfreie Stadt       1.0  ...
4          Brunsbüttel, Stadt                     Stadt       1.0  ...
...                       ...                       ...       ...  ...
10954             Göpfersdorf  Kreisangehörige Gemeinde      16.0  ...
10955  Langenleuba-Niederhain  Kreisangehörige Gemeinde      16.0  ...
10956                  Nobitz  Kreisangehörige Gemeinde      16.0  ...
10957              Dobitschen  Kreisangehörige Gemeinde      16.0  ...
10958         Schmölln, Stadt                     Stadt      16.0  ...

      Neue Postleitzahl               Finanzamtsbezirk          \
                nunique        unique          nunique  unique
0                     1  [24937*****]                1  [2115]
1                     1  [24103*****]                1  [2119]
2                     1  [23539*****]                1  [2122]
3                     1  [24534*****]                1  [2124]
4                     1  [25541     ]                1  [2123]
...                 ...           ...              ...     ...
10954                 1  [04618*****]                1  [4166]
10955                 1  [04618*****]                1  [4166]
10956                 1  [04603     ]                1  [4166]
10957                 1  [04626     ]                1  [4166]
10958                 1  [04626     ]                1  [4166]

      Gerichtsbarkeit         Arbeitsagenturbezirk           \
              nunique  unique              nunique   unique
0                   1  [1112]                    1  [11901]
1                   1  [1517]                    1  [13101]
2                   1  [1721]                    1  [13501]
3                   1  [1519]                    1  [13901]
4                   1  [1319]                    1  [12705]
...               ...     ...                  ...      ...
10954               1  [1201]                    1   [9403]
10955               1  [1201]                    1   [9403]
10956               1  [1201]                    1   [9403]
10957               1  [1201]                    1   [9403]
10958               1  [1201]                    1   [9403]

      Bundestagswahlkreise
                   nunique unique
0                        1    [1]
1                        1    [5]
2                        1   [11]
3                        1    [6]
4                        1    [3]
...                    ...    ...
10954                    1  [193]
10955                    1  [193]
10956                    1  [193]
10957                    1  [193]
10958                    1  [193]

[10959 rows x 39 columns]

In [587]:
# d_agg = {
#     col_BL_number : ['mean','count'],
#     col_REGBEZ_number : ['mean','count'],
#     col_KREIS_number : ['mean','count'],
#     col_VERBANDGEMEINDE_number : ['mean','count'],
#     col_GEMEINDE_number : ['mean','count'],
#     'EF1_Satzart' : ['count'],
#     'Bevölkerung, insgesamt' : ['sum','median','mean'],
#     'Fläche in ha' : ['sum','median','mean']
# }


# l_by = [
#     col_BL_name, col_BL_number,col_REGBEZ_number,col_KREIS_number, col_VERBANDGEMEINDE_number ,col_GEMEINDE_number,
#     # 'EF3_ARS',
#     'EF5_Verbandsbezeichnung', 'GEM_TYPE'
# ]

# # dict_rename_cols = {'EF1_Satzart', 'Gemeinde'}
# pdf_sum_ade7 = df_60.groupby(l_by).agg(d_agg).round(2)


# print(f'Rows = {df.shape}')
# # df_60_sum = df_60_sum.sort_values(by=['BL_name', 'mean'])

# # if is_cout_sum_added:
# #     totals = df.agg(['count', 'sum'])
# #     df = pd.concat([df, totals])
# #     df.index.names = [col_BL_name]
    
# #     #df.sort_values(by=[col_BL_name],axis=0)#,'BL_nr'])#,'mean'])

# pdf_sum_ade7 = pdf_sum_ade7.rename(columns={
#     col_BL_number: 'ADE2_LAND', 
#     col_REGBEZ_number: 'ADE3_REG_BEZ', 
#     col_KREIS_number: 'ADE4_KREIS',
#     col_VERBANDGEMEINDE_number: 'ADE5_VERB_GEM',
#     col_GEMEINDE_number: 'ADE6_GEMEINDE',
#     'EF1_Satzart': 'Anzahl_GEMEINDE', 
# })
# pdf_sum_ade7

Rows = (16012, 11)

                                                                                                                ADE2_LAND  \
                                                                                                                     mean
BL_name           BL_nr BEZ_NR KREIS_NR EF4_Verband GEM_NR EF5_Verbandsbezeichnung     GEM_TYPE
Baden-Württemberg 8     1      11       0           0      Stuttgart, Landeshauptstadt Stadtkreis                     8.0
                               15       3           3      Böblingen, Stadt            große Kreisstadt               8.0
                                        28          28     Leonberg, Stadt             große Kreisstadt               8.0
                                        29          29     Magstadt                    Kreisangehörige Gemeinde       8.0
                                        41          41     Renningen, Stadt            Stadt                          8.0
...                                                                                                                   ...
Thüringen         16    0      77       5051        11     Göpfersdorf                 Kreisangehörige Gemeinde      16.0
                                                    23     Langenleuba-Niederhain      Kreisangehörige Gemeinde      16.0
                                                    36     Nobitz                      Kreisangehörige Gemeinde      16.0
                                        5052        3      Dobitschen                  Kreisangehörige Gemeinde      16.0
                                                    43     Schmölln, Stadt             Stadt                         16.0

                                                                                                                       \
                                                                                                                count
BL_name           BL_nr BEZ_NR KREIS_NR EF4_Verband GEM_NR EF5_Verbandsbezeichnung     GEM_TYPE
Baden-Württemberg 8     1      11       0           0      Stuttgart, Landeshauptstadt Stadtkreis                   1
                               15       3           3      Böblingen, Stadt            große Kreisstadt             1
                                        28          28     Leonberg, Stadt             große Kreisstadt             1
                                        29          29     Magstadt                    Kreisangehörige Gemeinde     1
                                        41          41     Renningen, Stadt            Stadt                        1
...                                                                                                               ...
Thüringen         16    0      77       5051        11     Göpfersdorf                 Kreisangehörige Gemeinde     1
                                                    23     Langenleuba-Niederhain      Kreisangehörige Gemeinde     1
                                                    36     Nobitz                      Kreisangehörige Gemeinde     1
                                        5052        3      Dobitschen                  Kreisangehörige Gemeinde     1
                                                    43     Schmölln, Stadt             Stadt                        1

                                                                                                                ADE3_REG_BEZ  \
                                                                                                                        mean
BL_name           BL_nr BEZ_NR KREIS_NR EF4_Verband GEM_NR EF5_Verbandsbezeichnung     GEM_TYPE
Baden-Württemberg 8     1      11       0           0      Stuttgart, Landeshauptstadt Stadtkreis                        1.0
                               15       3           3      Böblingen, Stadt            große Kreisstadt                  1.0
                                        28          28     Leonberg, Stadt             große Kreisstadt                  1.0
                                        29          29     Magstadt                    Kreisangehörige Gemeinde          1.0
                                        41          41     Renningen, Stadt            Stadt                             1.0
...                                                                                                                      ...
Thüringen         16    0      77       5051        11     Göpfersdorf                 Kreisangehörige Gemeinde          0.0
                                                    23     Langenleuba-Niederhain      Kreisangehörige Gemeinde          0.0
                                                    36     Nobitz                      Kreisangehörige Gemeinde          0.0
                                        5052        3      Dobitschen                  Kreisangehörige Gemeinde          0.0
                                                    43     Schmölln, Stadt             Stadt                             0.0

                                                                                                                       \
                                                                                                                count
BL_name           BL_nr BEZ_NR KREIS_NR EF4_Verband GEM_NR EF5_Verbandsbezeichnung     GEM_TYPE
Baden-Württemberg 8     1      11       0           0      Stuttgart, Landeshauptstadt Stadtkreis                   1
                               15       3           3      Böblingen, Stadt            große Kreisstadt             1
                                        28          28     Leonberg, Stadt             große Kreisstadt             1
                                        29          29     Magstadt                    Kreisangehörige Gemeinde     1
                                        41          41     Renningen, Stadt            Stadt                        1
...                                                                                                               ...
Thüringen         16    0      77       5051        11     Göpfersdorf                 Kreisangehörige Gemeinde     1
                                                    23     Langenleuba-Niederhain      Kreisangehörige Gemeinde     1
                                                    36     Nobitz                      Kreisangehörige Gemeinde     1
                                        5052        3      Dobitschen                  Kreisangehörige Gemeinde     1
                                                    43     Schmölln, Stadt             Stadt                        1

                                                                                                                ADE4_KREIS  \
                                                                                                                      mean
BL_name           BL_nr BEZ_NR KREIS_NR EF4_Verband GEM_NR EF5_Verbandsbezeichnung     GEM_TYPE
Baden-Württemberg 8     1      11       0           0      Stuttgart, Landeshauptstadt Stadtkreis                     11.0
                               15       3           3      Böblingen, Stadt            große Kreisstadt               15.0
                                        28          28     Leonberg, Stadt             große Kreisstadt               15.0
                                        29          29     Magstadt                    Kreisangehörige Gemeinde       15.0
                                        41          41     Renningen, Stadt            Stadt                          15.0
...                                                                                                                    ...
Thüringen         16    0      77       5051        11     Göpfersdorf                 Kreisangehörige Gemeinde       77.0
                                                    23     Langenleuba-Niederhain      Kreisangehörige Gemeinde       77.0
                                                    36     Nobitz                      Kreisangehörige Gemeinde       77.0
                                        5052        3      Dobitschen                  Kreisangehörige Gemeinde       77.0
                                                    43     Schmölln, Stadt             Stadt                          77.0

                                                                                                                       \
                                                                                                                count
BL_name           BL_nr BEZ_NR KREIS_NR EF4_Verband GEM_NR EF5_Verbandsbezeichnung     GEM_TYPE
Baden-Württemberg 8     1      11       0           0      Stuttgart, Landeshauptstadt Stadtkreis                   1
                               15       3           3      Böblingen, Stadt            große Kreisstadt             1
                                        28          28     Leonberg, Stadt             große Kreisstadt             1
                                        29          29     Magstadt                    Kreisangehörige Gemeinde     1
                                        41          41     Renningen, Stadt            Stadt                        1
...                                                                                                               ...
Thüringen         16    0      77       5051        11     Göpfersdorf                 Kreisangehörige Gemeinde     1
                                                    23     Langenleuba-Niederhain      Kreisangehörige Gemeinde     1
                                                    36     Nobitz                      Kreisangehörige Gemeinde     1
                                        5052        3      Dobitschen                  Kreisangehörige Gemeinde     1
                                                    43     Schmölln, Stadt             Stadt                        1

                                                                                                                ADE5_VERB_GEM  \
                                                                                                                         mean
BL_name           BL_nr BEZ_NR KREIS_NR EF4_Verband GEM_NR EF5_Verbandsbezeichnung     GEM_TYPE
Baden-Württemberg 8     1      11       0           0      Stuttgart, Landeshauptstadt Stadtkreis                         0.0
                               15       3           3      Böblingen, Stadt            große Kreisstadt                   3.0
                                        28          28     Leonberg, Stadt             große Kreisstadt                  28.0
                                        29          29     Magstadt                    Kreisangehörige Gemeinde          29.0
                                        41          41     Renningen, Stadt            Stadt                             41.0
...                                                                                                                       ...
Thüringen         16    0      77       5051        11     Göpfersdorf                 Kreisangehörige Gemeinde        5051.0
                                                    23     Langenleuba-Niederhain      Kreisangehörige Gemeinde        5051.0
                                                    36     Nobitz                      Kreisangehörige Gemeinde        5051.0
                                        5052        3      Dobitschen                  Kreisangehörige Gemeinde        5052.0
                                                    43     Schmölln, Stadt             Stadt                           5052.0

                                                                                                                       \
                                                                                                                count
BL_name           BL_nr BEZ_NR KREIS_NR EF4_Verband GEM_NR EF5_Verbandsbezeichnung     GEM_TYPE
Baden-Württemberg 8     1      11       0           0      Stuttgart, Landeshauptstadt Stadtkreis                   1
                               15       3           3      Böblingen, Stadt            große Kreisstadt             1
                                        28          28     Leonberg, Stadt             große Kreisstadt             1
                                        29          29     Magstadt                    Kreisangehörige Gemeinde     1
                                        41          41     Renningen, Stadt            Stadt                        1
...                                                                                                               ...
Thüringen         16    0      77       5051        11     Göpfersdorf                 Kreisangehörige Gemeinde     1
                                                    23     Langenleuba-Niederhain      Kreisangehörige Gemeinde     1
                                                    36     Nobitz                      Kreisangehörige Gemeinde     1
                                        5052        3      Dobitschen                  Kreisangehörige Gemeinde     1
                                                    43     Schmölln, Stadt             Stadt                        1

                                                                                                                ADE6_GEMEINDE  \
                                                                                                                         mean
BL_name           BL_nr BEZ_NR KREIS_NR EF4_Verband GEM_NR EF5_Verbandsbezeichnung     GEM_TYPE
Baden-Württemberg 8     1      11       0           0      Stuttgart, Landeshauptstadt Stadtkreis                         0.0
                               15       3           3      Böblingen, Stadt            große Kreisstadt                   3.0
                                        28          28     Leonberg, Stadt             große Kreisstadt                  28.0
                                        29          29     Magstadt                    Kreisangehörige Gemeinde          29.0
                                        41          41     Renningen, Stadt            Stadt                             41.0
...                                                                                                                       ...
Thüringen         16    0      77       5051        11     Göpfersdorf                 Kreisangehörige Gemeinde          11.0
                                                    23     Langenleuba-Niederhain      Kreisangehörige Gemeinde          23.0
                                                    36     Nobitz                      Kreisangehörige Gemeinde          36.0
                                        5052        3      Dobitschen                  Kreisangehörige Gemeinde           3.0
                                                    43     Schmölln, Stadt             Stadt                             43.0

                                                                                                                       \
                                                                                                                count
BL_name           BL_nr BEZ_NR KREIS_NR EF4_Verband GEM_NR EF5_Verbandsbezeichnung     GEM_TYPE
Baden-Württemberg 8     1      11       0           0      Stuttgart, Landeshauptstadt Stadtkreis                   1
                               15       3           3      Böblingen, Stadt            große Kreisstadt             1
                                        28          28     Leonberg, Stadt             große Kreisstadt             1
                                        29          29     Magstadt                    Kreisangehörige Gemeinde     1
                                        41          41     Renningen, Stadt            Stadt                        1
...                                                                                                               ...
Thüringen         16    0      77       5051        11     Göpfersdorf                 Kreisangehörige Gemeinde     1
                                                    23     Langenleuba-Niederhain      Kreisangehörige Gemeinde     1
                                                    36     Nobitz                      Kreisangehörige Gemeinde     1
                                        5052        3      Dobitschen                  Kreisangehörige Gemeinde     1
                                                    43     Schmölln, Stadt             Stadt                        1

                                                                                                                Anzahl_GEMEINDE  \
                                                                                                                          count
BL_name           BL_nr BEZ_NR KREIS_NR EF4_Verband GEM_NR EF5_Verbandsbezeichnung     GEM_TYPE
Baden-Württemberg 8     1      11       0           0      Stuttgart, Landeshauptstadt Stadtkreis                             1
                               15       3           3      Böblingen, Stadt            große Kreisstadt                       1
                                        28          28     Leonberg, Stadt             große Kreisstadt                       1
                                        29          29     Magstadt                    Kreisangehörige Gemeinde               1
                                        41          41     Renningen, Stadt            Stadt                                  1
...                                                                                                                         ...
Thüringen         16    0      77       5051        11     Göpfersdorf                 Kreisangehörige Gemeinde               1
                                                    23     Langenleuba-Niederhain      Kreisangehörige Gemeinde               1
                                                    36     Nobitz                      Kreisangehörige Gemeinde               1
                                        5052        3      Dobitschen                  Kreisangehörige Gemeinde               1
                                                    43     Schmölln, Stadt             Stadt                                  1

                                                                                                                Bevölkerung, insgesamt  \
                                                                                                                                   sum
BL_name           BL_nr BEZ_NR KREIS_NR EF4_Verband GEM_NR EF5_Verbandsbezeichnung     GEM_TYPE
Baden-Württemberg 8     1      11       0           0      Stuttgart, Landeshauptstadt Stadtkreis                               633484
                               15       3           3      Böblingen, Stadt            große Kreisstadt                          52093
                                        28          28     Leonberg, Stadt             große Kreisstadt                          49845
                                        29          29     Magstadt                    Kreisangehörige Gemeinde                   9807
                                        41          41     Renningen, Stadt            Stadt                                     18655
...                                                                                                                                ...
Thüringen         16    0      77       5051        11     Göpfersdorf                 Kreisangehörige Gemeinde                    220
                                                    23     Langenleuba-Niederhain      Kreisangehörige Gemeinde                   1717

In [355]:
pdf_sum_de.to_csv('GV100_20241031_clean.csv')

### Gemeinden in Deutschland

Deutschland verfügt über insgesamt 11.000 Kommunen, von denen die meisten Gemeinden sind. Nach den aktuellen Zahlen gibt es:

- Rheinland-Pfalz: 2.301 Gemeinden
- Bayern: 2.056 Gemeinden
- Schleswig-Holstein: 1.106 Gemeinden
- Baden-Württemberg: 1.101 Gemeinden
- Niedersachsen: 941 Gemeinden
- Mecklenburg-Vorpommern: 726 Gemeinden
- Thüringen: 631 Gemeinden
- Hessen: 422 Gemeinden
- Sachsen: 419 Gemeinden
- Brandenburg: 416 Gemeinden
- Nordrhein-Westfalen: 396 Gemeinden
- Sachsen-Anhalt: 218 Gemeinden
- Saarland: 52 Gemeinden
- Bremen: 2 Gemeinden
- Hamburg: 1 Gemeinde
- Berlin: 1 Gemeinde

# REST

In [42]:
df_gmd_02 = df[df['BL_nr'] == '02']
df_gmd_02

,EF1_Satzart,EF2_Gebietstand,EF3_ARS,EF4_Verband,EF5_Verbandsbezeichnung,EF6_Sitz_des_Verbandes,EF7_Schlüsselfelder,EF8_Leer,EF9_Frei für landesinterne Angaben,BL_nr
1293,10,20241031,02,NaN,Hamburg,Hamburg,NaN,NaN,NaN,02
1294,40,20241031,02000,NaN,"Hamburg, Freie und Hansestadt",Hamburg,41.0,NaN,NaN,02
1295,50,20241031,02000,0.0,"Hamburg, Freie und Hansestadt",NaN,50.0,NaN,NaN,02
1296,60,20241031,02000000,0.0,"Hamburg, Freie und Hansestadt",NaN,61.0,000000755090000191016000000936740 20038****...,NaN,02

In [61]:
df.head(5)

,EF1_Satzart,EF2_Gebietstand,EF3_ARS,EF4_Verband,EF5_Verbandsbezeichnung,EF6_Sitz_des_Verbandes,EF7_Schlüsselfelder,EF8_Leer,EF9_Frei für landesinterne Angaben,BL_nr
0,10,20241031,01,NaN,Schleswig-Holstein,Kiel,NaN,NaN,NaN,01
1,40,20241031,01001,NaN,"Flensburg, Stadt",Flensburg,41.0,NaN,NaN,01
2,50,20241031,01001,0.0,"Flensburg, Stadt",NaN,50.0,NaN,NaN,01
3,60,20241031,01001000,0.0,"Flensburg, Stadt",NaN,61.0,000000056730000009266700000045905 24937****...,NaN,01
4,40,20241031,01002,NaN,"Kiel, Landeshauptstadt",Kiel,41.0,NaN,NaN,01

In [77]:
cond_bl = df['BL_nr'] == '03'
cond_satzart_20 = df['EF1_Satzart'] == 20
cond_satzart_30 = df['EF1_Satzart'] == 30
df[cond_bl & cond_satzart]

,EF1_Satzart,EF2_Gebietstand,EF3_ARS,EF4_Verband,EF5_Verbandsbezeichnung,EF6_Sitz_des_Verbandes,EF7_Schlüsselfelder,EF8_Leer,EF9_Frei für landesinterne Angaben,BL_nr
1298,20,20241031,031,NaN,Statistische Region Braunschweig,NaN,NaN,NaN,NaN,03
1568,20,20241031,032,NaN,Statistische Region Hannover,NaN,NaN,NaN,NaN,03
1879,20,20241031,033,NaN,Statistische Region Lüneburg,NaN,NaN,NaN,NaN,03
2331,20,20241031,034,NaN,Statistische Region Weser-Ems,NaN,NaN,NaN,NaN,03

In [81]:
df[cond_satzart_20]

,EF1_Satzart,EF2_Gebietstand,EF3_ARS,EF4_Verband,EF5_Verbandsbezeichnung,EF6_Sitz_des_Verbandes,EF7_Schlüsselfelder,EF8_Leer,EF9_Frei für landesinterne Angaben,BL_nr
1298,20,20241031,031,NaN,Statistische Region Braunschweig,NaN,NaN,NaN,NaN,03
1568,20,20241031,032,NaN,Statistische Region Hannover,NaN,NaN,NaN,NaN,03
1879,20,20241031,033,NaN,Statistische Region Lüneburg,NaN,NaN,NaN,NaN,03
2331,20,20241031,034,NaN,Statistische Region Weser-Ems,NaN,NaN,NaN,NaN,03
2747,20,20241031,051,NaN,Reg.-Bez. Düsseldorf,Düsseldorf,NaN,NaN,NaN,05
2895,20,20241031,053,NaN,Reg.-Bez. Köln,Köln,NaN,NaN,NaN,05
3105,20,20241031,055,NaN,Reg.-Bez. Münster,Münster,NaN,NaN,NaN,05
3270,20,20241031,057,NaN,Reg.-Bez. Detmold,Detmold,NaN,NaN,NaN,05
3418,20,20241031,059,NaN,Reg.-Bez. Arnsberg,Arnsberg,NaN,NaN,NaN,05
3598,20,20241031,064,NaN,Reg.-Bez. Darmstadt,Darmstadt,NaN,NaN,NaN,06
3985,20,20241031,065,NaN,Reg.-Bez. Gießen,Gießen,NaN,NaN,NaN,06
4193,20,20241031,066,NaN,Reg.-Bez. Kassel,Kassel,NaN,NaN,NaN,06
4480,20,20241031,071,NaN,früher: Reg.-Bez. Koblenz,"Koblenz, Stadt",NaN,NaN,NaN,07
5671,20,20241031,072,NaN,früher: Reg.-Bez. Trier,"Trier, Stadt",NaN,NaN,NaN,07
6254,20,20241031,073,NaN,früher: Reg.-Bez. Rheinhessen-Pfalz,"Neustadt a. d. Weinstraße, Stadt",NaN,NaN,NaN,07
6991,20,20241031,081,NaN,Reg.-Bez. Stuttgart,Stuttgart,NaN,NaN,NaN,08
7506,20,20241031,082,NaN,Reg.-Bez. Karlsruhe,Karlsruhe,NaN,NaN,NaN,08
7842,20,20241031,083,NaN,Reg.-Bez. Freiburg,Freiburg im Breisgau,NaN,NaN,NaN,08
8260,20,20241031,084,NaN,Reg.-Bez. Tübingen,Tübingen,NaN,NaN,NaN,08
8617,20,20241031,091,NaN,Oberbayern,München,NaN,NaN,NaN,09
9558,20,20241031,092,NaN,Niederbayern,Landshut,NaN,NaN,NaN,09
10052,20,20241031,093,NaN,Oberpfalz,Regensburg,NaN,NaN,NaN,09
10462,20,20241031,094,NaN,Oberfranken,Bayreuth,NaN,NaN,NaN,09
10929,20,20241031,095,NaN,Mittelfranken,Ansbach,NaN,NaN,NaN,09
11349,20,20241031,096,NaN,Unterfranken,Würzburg,NaN,NaN,NaN,09
11947,20,20241031,097,NaN,Schwaben,Augsburg,NaN,NaN,NaN,09
14097,20,20241031,145,NaN,früher: Direktionsbezirk Chemnitz,Chemnitz,NaN,NaN,NaN,14
14424,20,20241031,146,NaN,früher: Direktionsbezirk Dresden,Chemnitz,NaN,NaN,NaN,14
14724,20,20241031,147,NaN,früher: Direktionsbezirk Leipzig,Chemnitz,NaN,NaN,NaN,14

In [78]:
df[cond_satzart_20].groupby('BL_nr')['EF5_Verbandsbezeichnung'].count().to_frame()#.agg(['EF5_Verbandsbezeichnung','count'])#count()#.to_frame()#.shape

       EF5_Verbandsbezeichnung
BL_nr
03                           4
05                           5
06                           3
07                           3
08                           4
09                           7
14                           3

In [80]:
df[cond_satzart_30]

,EF1_Satzart,EF2_Gebietstand,EF3_ARS,EF4_Verband,EF5_Verbandsbezeichnung,EF6_Sitz_des_Verbandes,EF7_Schlüsselfelder,EF8_Leer,EF9_Frei für landesinterne Angaben,BL_nr
6992,30,20241031,0811,NaN,Region Stuttgart,Stuttgart,NaN,NaN,NaN,08
7261,30,20241031,0812,NaN,Region Heilbronn-Franken,Heilbronn,NaN,NaN,NaN,08
7428,30,20241031,0813,NaN,Region Ostwürttemberg,Schwäbisch Gmünd,NaN,NaN,NaN,08
7507,30,20241031,0821,NaN,Region Mittlerer Oberrhein,Karlsruhe,NaN,NaN,NaN,08
7604,30,20241031,0822,NaN,Region Rhein-Neckar,Mannheim,NaN,NaN,NaN,08
7734,30,20241031,0823,NaN,Region Nordschwarzwald,Pforzheim,NaN,NaN,NaN,08
7843,30,20241031,0831,NaN,Region Südlicher Oberrhein,Freiburg im Breisgau,NaN,NaN,NaN,08
8024,30,20241031,0832,NaN,Region Schwarzwald-Baar-Heuberg,Villingen-Schwenningen,NaN,NaN,NaN,08
8127,30,20241031,0833,NaN,Region Hochrhein-Bodensee,Waldshut-Tiengen,NaN,NaN,NaN,08
8261,30,20241031,0841,NaN,Region Neckar-Alb,Mössingen,NaN,NaN,NaN,08
8366,30,20241031,0842,NaN,Region Donau-Iller,Ulm,NaN,NaN,NaN,08
8495,30,20241031,0843,NaN,Region Bodensee-Oberschwaben,Ravensburg,NaN,NaN,NaN,08

In [79]:
df[cond_satzart_30].groupby('BL_nr')['EF5_Verbandsbezeichnung'].count().to_frame()

       EF5_Verbandsbezeichnung
BL_nr
08                          12

## PARSING SATZ60

# EF8      129-139     11     C NOV11K00     Fläche in ha
# EF9      140-150     11     C NOV11K00     Bevölkerung, insgesamt
# EF10     151-161     11     C NOV11K00     Bevölkerung, männlich
# EF11     162-165      4     C      ALN     Leer
# EF12     166-175     10                    Neue Postleitzahl
#  EF12U1  166-170      5     C      ALN      PLZ der Gemeinde (bei mehreren Postleitzahlen - PLZ des Verwaltungssitzes)
#  EF12U2  171-175      5     C      ALN      Kennzeichnung, ob PLZ eindeutig (leer = Gemeinde hat nur eine PLZ, sonst = Gemeinde hat mehrere PLZ)
# EF13     176-177      2     C      ALN     LEER
# EF14     178-181      4     C      ALN     Finanzamtsbezirk
# EF15     182-185      5                    Gerichtsbarkeit
#  EF15U1  182-183      2     C      ALN      Oberlandesgerichtsbezirk
#  EF15U2  184          1     C      ALN      Landgerichtsbezirk
#  EF15U3  185          1     C      ALN      Amtsgerichtsbezirk
# EF16     186-190      5     C      ALN     Arbeitsagenturbezirk
# EF17     191-196      6                    Bundestagswahlkreise
#  EF17U1  191-193      3     C      ALN      Bundestagswahlkreis
#  EF17U2  194-196      3     C      ALN      Bundestagswahlkreis
# EF18     197-200      2     C      ALN    Leer

,EF1_Satzart,EF2_Gebietstand,EF3_ARS,EF4_Verband,EF5_Verbandsbezeichnung,EF6_Sitz_des_Verbandes,EF7_Schlüsselfelder,EF8_Leer,EF9_Frei für landesinterne Angaben,BL_nr
3,60,20241031,01001000,0.0,"Flensburg, Stadt",NaN,61.0,000000056730000009266700000045905 24937****...,NaN,01
6,60,20241031,01002000,0.0,"Kiel, Landeshauptstadt",NaN,61.0,000000118650000024887300000120699 24103****...,NaN,01
9,60,20241031,01003000,0.0,"Lübeck, Hansestadt",NaN,61.0,000000214190000021904400000105259 23539****...,NaN,01
12,60,20241031,01004000,0.0,"Neumünster, Stadt",NaN,61.0,000000071660000008018500000039772 24534****...,NaN,01
22,60,20241031,01051001,5175.0,Albersdorf,NaN,64.0,000000017120000000384700000001855 25767 ...,NaN,01

C:\Users\gujua\AppData\Local\Temp\ipykernel_11768\3689286373.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_60[field] = df_60.EF8_Leer.str[pos_start:pos_end]
C:\Users\gujua\AppData\Local\Temp\ipykernel_11768\3689286373.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_60[field] = df_60[field].fillna(0)
C:\Users\gujua\AppData\Local\Temp\ipykernel_11768\3689286373.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_60[field] = df_60[field].astype(field_type)
C:\Users\gujua\AppData\Local\Temp\ipykernel_11768\3689286373.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_60[field] = df_60.EF8_Leer.str[pos_start:pos_end]
C:\Users\gujua\AppData\Local\Temp\ipykernel_11768\3689286373.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_60[field] = df_60[field].fillna(0)
C:\Users\gujua\AppData\Local\Temp\ipykernel_11768\3689286373.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_60[field] = df_60[field].astype(field_type)
C:\Users\gujua\AppData\Local\Temp\ipykernel_11768\3689286373.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_60[field] = df_60.EF8_Leer.str[pos_start:pos_end]
C:\Users\gujua\AppData\Local\Temp\ipykernel_11768\3689286373.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_60[field] = df_60[field].fillna(0)
C:\Users\gujua\AppData\Local\Temp\ipykernel_11768\3689286373.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_60[field] = df_60[field].astype(field_type)
C:\Users\gujua\AppData\Local\Temp\ipykernel_11768\3689286373.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_60[field] = df_60.EF8_Leer.str[pos_start:pos_end]
C:\Users\gujua\AppData\Local\Temp\ipykernel_11768\3689286373.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_60[field] = df_60.EF8_Leer.str[pos_start:pos_end]
C:\Users\gujua\AppData\Local\Temp\ipykernel_11768\3689286373.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_60[field] = df_60.EF8_Leer.str[pos_start:pos_end]
C:\Users\gujua\AppData\Local\Temp\ipykernel_11768\3689286373.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_60[field] = df_60.EF8_Leer.str[pos_start:pos_end]
C:\Users\gujua\AppData\Local\Temp\ipykernel_11768\3689286373.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_60[field] = df_60.EF8_Leer.str[pos_start:pos_end]

,EF1_Satzart,EF2_Gebietstand,EF3_ARS,EF4_Verband,EF5_Verbandsbezeichnung,EF6_Sitz_des_Verbandes,EF7_Schlüsselfelder,EF8_Leer,EF9_Frei für landesinterne Angaben,BL_nr,Fläche in ha,"Bevölkerung, insgesamt","Bevölkerung, männlich",Neue Postleitzahl,Finanzamtsbezirk,Gerichtsbarkeit,Arbeitsagenturbezirk,Bundestagswahlkreise
3,60,20241031,01001000,0.0,"Flensburg, Stadt",NaN,61.0,000000056730000009266700000045905 24937****...,NaN,01,567,9266,4590,24937****,211,1112,1901,01
6,60,20241031,01002000,0.0,"Kiel, Landeshauptstadt",NaN,61.0,000000118650000024887300000120699 24103****...,NaN,01,1186,24887,12069,24103****,211,1517,3101,05
9,60,20241031,01003000,0.0,"Lübeck, Hansestadt",NaN,61.0,000000214190000021904400000105259 23539****...,NaN,01,2141,21904,10525,23539****,212,1721,3501,11
12,60,20241031,01004000,0.0,"Neumünster, Stadt",NaN,61.0,000000071660000008018500000039772 24534****...,NaN,01,716,8018,3977,24534****,212,1519,3901,06
22,60,20241031,01051001,5175.0,Albersdorf,NaN,64.0,000000017120000000384700000001855 25767 ...,NaN,01,171,384,185,25767,212,1319,2701,03
23,60,20241031,01051002,5175.0,Arkebek,NaN,64.0,000000006920000000022900000000125 25767 ...,NaN,01,69,22,12,25767,212,1319,2701,03
24,60,20241031,01051003,5163.0,Averlak,NaN,64.0,000000009060000000058700000000301 25715 ...,NaN,01,90,58,30,25715,212,1319,2705,03
25,60,20241031,01051004,5175.0,Bargenstedt,NaN,64.0,000000011900000000098100000000477 25704 ...,NaN,01,119,98,47,25704,212,1319,2713,03
26,60,20241031,01051005,5169.0,Barkenholm,NaN,64.0,000000005110000000016800000000093 25791 ...,NaN,01,51,16,9,25791,211,1319,2701,02
27,60,20241031,01051006,5175.0,Barlt,NaN,64.0,000000022880000000076400000000382 25719 ...,NaN,01,228,76,38,25719,212,1319,2713,03

In [154]:
l_agg = ['Bevölkerung, insgesamt', 'Bevölkerung, männlich']
df_60group = df_60.groupby('BL_nr')[l_agg].sum()#.to_frame()
df_60group['bev, prozent, mann [%]'] = df_60group['Bevölkerung, männlich']/df_60group['Bevölkerung, insgesamt']
df_60group['bev, prozent, mann [%]'] = df_60group['bev, prozent, mann [%]'].round(3)*100

df_60group# df_60_int = df_60group(l_agg)

       Bevölkerung, insgesamt  Bevölkerung, männlich  bev, prozent, mann [%]
BL_nr
01                     296062                 144628                    48.9
02                     191016                  93674                    49.0
03                     815768                 402201                    49.3
04                      69169                  34198                    49.4
05                    1818864                 892902                    49.1
06                     641882                 316893                    49.4
07                     416373                 205569                    49.4
08                    1133444                 562877                    49.7
09                    1342580                 665521                    49.6
10                      99418                  48877                    49.2
11                     378220                 186011                    49.2
12                     257989                 126923                    49.2
13                     162626                  79778                    49.1
14                     408755                 201408                    49.3
15                     217942                 107189                    49.2
16                     211964                 104813                    49.4

In [117]:
df_60['Bevölkerung, insgesamt'].sum()

846693260

In [ ]:
def